config/routes.rb
Houston::Alerts::Engine.routes.draw do

  scope "alerts" do
    get "", to: "alerts#index", as: :alerts
    get "excel", to: "alerts#excel", as: :alerts_excel
    get "dashboard", to: "alerts#dashboard"

    match ":id", to: "alerts#update", via: [:put, :patch]

    namespace "api" do
      namespace "v1" do
        get "alerts", to: "alerts#index"
        get "alerts/mine", to: "alerts#mine"
      end
    end
  end

  constraints type: Regexp.union(Houston::Alerts.config.types) do
    get ":type/:number", to: "alerts#show", as: :alert
  end

end

app/models/houston/alerts/alert.rb
module Houston
  module Alerts
    class Alert < ActiveRecord::Base
      include Houston::Props

      attr_accessor :updated_by

      self.table_name = "alerts"
      self.inheritance_column = nil

      belongs_to :project, class_name: "::Project", optional: true
      belongs_to :checked_out_by, class_name: "::User", optional: true
      has_and_belongs_to_many :commits, class_name: "::Commit"
      has_many :pull_requests, through: :commits, class_name: "Github::PullRequest"

      after_initialize { self.opened_at ||= Time.now }

      default_scope { unsuppressed.where(destroyed_at: nil).order(:deadline) }

      validates :type, :key, :summary, :url, :opened_at, :number, presence: true
      validates :priority, presence: true, inclusion: {:in => %w{high urgent}}

      before_save :update_checked_out_by, :if => :checked_out_by_email_changed?
      before_save :update_project, :if => :project_slug_changed?
      before_save :update_deadline, :if => :opened_at_or_priority_changed?

      after_create do
        Houston.observer.fire "alert:create", alert: self
        Houston.observer.fire "alert:#{type}:create", alert: self
      end

      after_update do
        Houston.observer.fire "alert:update", alert: self
        Houston.observer.fire "alert:#{type}:update", alert: self
        if saved_change_to_checked_out_by_id?
          Houston.observer.fire "alert:assign", alert: self
          Houston.observer.fire "alert:#{type}:assign", alert: self
        end
        if saved_change_to_closed_at?
          if closed_at
            Houston.observer.fire "alert:close", alert: self
            Houston.observer.fire "alert:#{type}:close", alert: self
          else
            Houston.observer.fire "alert:reopen", alert: self
            Houston.observer.fire "alert:#{type}:reopen", alert: self
          end
        end
        if saved_change_to_destroyed_at?
          if destroyed_at
            Houston.observer.fire "alert:destroy", alert: self
            Houston.observer.fire "alert:#{type}:destroy", alert: self
          else
            Houston.observer.fire "alert:restore", alert: self
            Houston.observer.fire "alert:#{type}:restore", alert: self
          end
        end
      end



      class << self
        def open(options={})
          if options.key?(:at)
            time = options[:at]
            where(
              arel_table[:opened_at].lteq(time)
            ).where(
              arel_table[:closed_at].gt(time).or(
              arel_table[:closed_at].eq(nil))
            )
          else
            where(closed_at: nil)
          end
        end

        def closed(options={})
          if options.key?(:after)
            where(arel_table[:closed_at].gteq(options[:after]))
          else
            where(arel_table[:closed_at].not_eq(nil))
          end
        end

        def closed_on_time
          closed.where(arel_table[:closed_at].lteq(arel_table[:deadline]))
        end

        def closed_on(date)
          where(closed_at: date.to_time.beginning_of_day..date.to_time.end_of_day)
        end

        def checked_out
          where(arel_table[:checked_out_by_id].not_eq(nil))
        end

        def checked_out_by(user)
          where(checked_out_by_id: user.id)
        end

        def due_before(time)
          where(arel_table[:deadline].lteq(time))
        end

        def due_after(time)
          where(arel_table[:deadline].gt(time))
        end

        def due_since(time)
          where(arel_table[:deadline].gteq(time))
        end

        def closed_or_due_during(range)
          range = range.to_range if range.respond_to?(:to_range)
          where(
            arel_table[:deadline].in(range).or(
            arel_table[:closed_at].in(range)
          ))
        end

        def without_keys(*keys)
          where(arel_table[:key].not_in(keys.flatten))
        end

        def destroyed
          unscoped.where(arel_table[:destroyed_at].not_eq nil)
        end

        def with_destroyed
          unscope(where: :destroyed_at)
        end

        def unsuppressed
          where(suppressed: false)
        end

        def with_suppressed
          unscope(where: :suppressed)
        end

        def synchronize(mode, type, alerts)
          case mode
          when :all then with_suppressed.synchronize_all(type, alerts)
          when :open then with_suppressed.synchronize_open(type, alerts)
          when :changes then with_suppressed.synchronize_changes(type, alerts)
          else raise NotImplementedError, "I don't know how to synchronize #{mode.inspect}"
          end
        end

        def synchronize_open(type, open_alerts)
          Houston.benchmark("[alerts:sync:#{type}/open] #{open_alerts.length} open #{type.pluralize}") do
            open_alerts.uniq! { |alert| alert.fetch(:key) }
            open_alerts_keys = open_alerts.map { |attrs| attrs.fetch(:key) }

            # Close alerts that are no longer open
            open
              .where(type: type)
              .without_keys(open_alerts_keys)
              .close!

            # Reopen alerts that were closed prematurely
            closed
              .where(type: type)
              .where(key: open_alerts_keys)
              .reopen!

            # Load currently open alerts so that they may be
            # compared to the new open alerts
            existing_alerts = open.where(type: type, key: open_alerts_keys)
            existing_alerts_keys = existing_alerts.map(&:key)

            # Create current alerts that don't exist
            open_alerts.each do |attrs|
              next if existing_alerts_keys.member? attrs.fetch(:key)
              _create attrs.merge(type: type)
            end

            # Update existing alerts that are current
            existing_alerts.each do |existing_alert|
              current_attrs = open_alerts.detect { |attrs| attrs.fetch(:key) == existing_alert.key }
              _update existing_alert, current_attrs
            end
          end; nil
        end

        def synchronize_all(type, expected_alerts)
          Houston.benchmark("[alerts:sync:#{type}/all] #{expected_alerts.length} #{type.pluralize}") do
            expected_alerts.uniq! { |alert| alert.fetch(:key) }
            expected_alerts_keys = expected_alerts.map { |attrs| attrs.fetch(:key) }

            # Prune alerts that were deleted remotely
            all
              .where(type: type)
              .without_keys(expected_alerts_keys)
              .destroy!

            # Resurrect alerts that were deleted prematurely
            destroyed
              .where(type: type)
              .where(key: expected_alerts_keys)
              .undestroy!

            # Load existing alerts so that they may be
            # compared to the new expected alerts.
            # NB: This could grow to be a large number of objects!
            existing_alerts = where(type: type, key: expected_alerts_keys)
            existing_alerts_keys = existing_alerts.map(&:key)

            # Create current alerts that don't exist
            expected_alerts.each do |attrs|
              next if existing_alerts_keys.member? attrs.fetch(:key)
              _create attrs.merge(type: type)
            end

            # Update existing alerts that are current
            existing_alerts.each do |existing_alert|
              current_attrs = expected_alerts.detect { |attrs| attrs.fetch(:key) == existing_alert.key }
              _update existing_alert, current_attrs
            end
          end; nil
        end

        def synchronize_changes(type, changed_alerts)
          Houston.benchmark("[alerts:sync:#{type}/changed] #{changed_alerts.length} changed #{type.pluralize}") do
            changed_alerts.uniq! { |alert| alert.fetch(:key) }
            changed_alerts_keys = changed_alerts.map { |attrs| attrs.fetch(:key) }

            # Load existing alerts so that they may be
            # compared to the new expected alerts.
            existing_alerts = with_destroyed.where(type: type, key: changed_alerts_keys)
            existing_alerts_keys = existing_alerts.map(&:key)

            # Create current alerts that don't exist
            changed_alerts.each do |attrs|
              next if existing_alerts_keys.member? attrs.fetch(:key)
              _create attrs.merge(type: type)
            end

            # Update existing alerts that are current
            # (This may involve setting or clearing destroyed_at)
            existing_alerts.each do |existing_alert|
              current_attrs = changed_alerts.detect { |attrs| attrs.fetch(:key) == existing_alert.key }
              _update existing_alert, current_attrs
            end
          end; nil
        end

        def _create(attrs)
          return if attrs[:destroyed_at].present?

          new_alert = create(attrs)
          unless new_alert.valid?
            Rails.logger.warn "\e[31mFailed to create alert #{new_alert.key}: #{new_alert.errors.full_messages.to_sentence}\e[0m"
          end
        rescue ActiveRecord::RecordNotUnique
          # this alert was created simultaneously in another thread.
          # that's OK
        end

        def _update(existing_alert, attributes)
          attributes[:props] = existing_alert.props.to_h.merge(attributes.fetch(:props, {}))
          existing_alert.attributes = attributes if attributes
          if existing_alert.changed? && !existing_alert.save
            Rails.logger.warn "\e[31mFailed to update alert #{existing_alert.key}: #{existing_alert.errors.full_messages.to_sentence}\e[0m"
          end
        end

        def close!
          all.each(&:close!)
        end

        def reopen!
          all.each(&:reopen!)
        end

        def destroy!
          all.each { |alert| alert.update_attribute! :destroyed_at, Time.now }
        end

        def undestroy!
          all.each { |alert| alert.update_attribute! :destroyed_at, nil }
        end
      end

app/controllers/houston/alerts/alerts_controller.rb
module Houston
  module Alerts
    class AlertsController < ApplicationController
      helper "houston/alerts/alert"
      layout "houston/alerts/application"
      skip_before_action :verify_authenticity_token, only: [:time]
      before_action :fetch_alerts, only: [:index, :dashboard]


      def index
        authorize! :read, Alert unless request.xhr?
        @alerts = @alerts.with_suppressed
        @title = "Alerts (#{@alerts.reject(&:suppressed?).count})"
      end

      def dashboard
        @limit = params[:limit].to_i
        @count = @alerts.count
        @title = "Alerts (#{@count})"
        @alerts = @alerts.limit(@limit) if @limit > 0

        respond_to do |format|
          format.json { render json: {alerts: AlertPresenter.new(@alerts), count: @count} }
          format.html { render layout: "houston/alerts/dashboard" }
        end
      end


      def show
        @alert = Alert.with_suppressed.find_by!(type: params[:type], number: params[:number])
        redirect_to @alert.url unless unfurling?
      end



      def excel
        authorize! :read, Alert
        alerts = Alert.includes(:project, :checked_out_by)
        send_data AlertExcelPresenter.new(alerts),
          type: :xlsx,
          filename: "Alerts.xlsx",
          disposition: "attachment"
      end


      def update
        alert = Alert.with_suppressed.find(params[:id])
        authorize! :update, alert
        attributes = params.permit(:checked_out_by_id, :suppressed).to_h
        attributes[:project_id] = params[:project_id] if alert.can_change_project? && params.key?(:project_id)
        alert.updated_by = current_user
        if alert.update_attributes(attributes)
          render json: Houston::Alerts::AlertPresenter.new(alert)
        else
          render json: alert.errors, status: :unprocessable_entity
        end
      end


    private

      def fetch_alerts
        @projects = ::Project.unretired.pluck(:id, :name)
          .find_all { |id, name| can?(:manage, Houston::Alerts::Alert.new(project_id: id)) }
          .map { |id, name| { id: id, name: name } }

        teams = Team.none
        teams = current_user.teams if current_user
        params[:teams] = params[:team] if params.key?(:team) && !params.key?(:teams)
        teams = Team.where(id: params[:teams].split(",")) if params.key?(:teams)

        @alerts = Alert.open.preload(:project, :checked_out_by, :pull_requests)
          .where(project_id: teams.project_ids)
        @alerts = @alerts.joins(:project)
          .where(::Project.arel_table[:slug].in params[:only].split(",")) if params.key?(:only)
        @alerts = @alerts.joins(:project)
          .where(::Project.arel_table[:slug].not_in params[:except].split(",")) if params.key?(:except)
      end

    end
  end
end

app/controllers/houston/alerts/api/v1/alerts_controller.rb
module Houston
  module Alerts
    module Api
      module V1
        class AlertsController < ApplicationController
          attr_reader :alerts

          before_action :api_authenticate!, :get_alerts
          skip_before_action :verify_authenticity_token


          def index
            render json: AlertPresenter.new(alerts)
          end

          def mine
            alerts = self.alerts.checked_out_by(current_user)
            render json: AlertPresenter.new(alerts)
          end


        private

          def get_alerts
            closed = params[:closed] && Date.parse(params[:closed]) rescue nil
            @alerts = closed ? Alert.closed_on(closed) : Alert.open
          end

        end
      end
    end
  end
end

app/helpers/houston/alerts/alert_helper.rb
module Houston::Alerts
  module AlertHelper

    def icon_for_alert(alert)
      "<i class=\"fa #{_icon_for_type(alert.type)}\"></i>".html_safe
    end

    def format_alert_deadline(alert)
      deadline = alert.deadline
      due_date = deadline.to_date
      today = Date.today

      if due_date < today
        "Past"
      elsif due_date == today
        deadline.strftime("%-I:%M %P")
      elsif due_date == today + 1
        deadline.strftime("%-I:%M %P<span class=\"weekday\">Tomorrow</span>").html_safe
      else
        deadline.strftime("%-I:%M %P<span class=\"weekday\">%A</span>").html_safe
      end
    end

    def _icon_for_type(type)
      Houston::Alerts.config.icons_by_type.fetch type
    end

  end
end

app/views/houston/alerts/alerts/dashboard.html.erb
<h1>Alerts</h1>

<span class="label" id="alerts_count">0</span>

<table id="alerts"></table>

<a id="toggle_audio_btn"></a>

<%= content_for :javascripts do %>
<script type="text/javascript">
  $(function() {
    var $alerts = $('#alerts'),
        format = d3.format('02d'),
        dateFormat = d3.time.format('<span class="label">%a</span> %-I:%M%p'),
        soundEffects = <%=raw MultiJson.dump(Houston::Alerts.config.sounds) %>,
        $countdowns, $countdown, urgent, label, timeleft, seconds, minutes, hours, days, date,
        limit = <%= @limit %>,
        newAlertIds, lastAlertIds,
        COUNTDOWN_STARTS = 36000, // 10 hours in seconds
        shouldPlaySounds = <%= MultiJson.dump(params[:sounds] == "on") %>,
        $audioToggle = $('#toggle_audio_btn'),
        formatMinutes;

    function formatDate(date) {
      return dateFormat(date).replace(/([AP])M$/, function(_, ap) { return ap.toLowerCase(); })
    }

    function playSample(effectName) {
      if(shouldPlaySounds) {
        var paths = soundEffects[effectName];
        if(paths && paths.length) {
          var path = paths[Math.floor(Math.random() * paths.length)];
          console.log('[play] playing "' + effectName + '": ' + path);
          Houston.play(path);
        } else {
          console.log('[play] playing "' + effectName + '": no audio file');
        }
      }
    }

    function updateCountdowns() {
      $countdowns = $countdowns || $('.countdown');
      urgent = false;
      $countdowns.each(function() {
        $countdown = $(this);
        timeleft = +$countdown.attr('data-secondsleft') - 1;
        $countdown.attr('data-secondsleft', timeleft);
        $countdown.closest('tr').toggleClass('late', timeleft < 0);

        if(timeleft < COUNTDOWN_STARTS) {
          seconds = Math.abs(timeleft);
          minutes = Math.floor(seconds / 60);
          hours = Math.floor(minutes / 60);
          days = Math.floor(hours / 24);

          label = format(seconds % 60);
          formatMinutes = (seconds < 3600) ? Math.floor : format;
          if(minutes >= 1) label = formatMinutes(minutes % 60) + ':' + label;
          if(hours >= 1) label = Math.floor(hours % 24) + ':' + label;
          if(days >= 1) label = '<span class="label">' + Math.floor(days) + 'd</span> ' + label;
          if(timeleft < 0) label = '<span class="late">+ ' + label + '</span>';
          $countdown.html(label);

          if(timeleft < 1800) urgent = true; // less than 30 minutes to go or late
        } else {
          date = timeleft.seconds().after(new Date());
          $countdown.html(formatDate(date));
        }
      });
      $('body').toggleClass('red', urgent);
    }

    function renderAlerts(data) {
      var alertsByDate = _.chain(data.alerts)
        .groupBy(function(alert) { return alert.deadline.substr(0,10) })
        .map(function(alerts, date) { return {alerts: alerts}; })
        .value();

      $('#alerts').html(HandlebarsTemplates['houston/alerts/dashboard']({dates: alertsByDate}));
      $('body').toggleClass('green', data.count == 0);
      $('#alerts_count').html(data.count);
      $('title').html('Alerts (' + data.count + ')')

      newAlertIds = _.pluck(data.alerts, 'id');
      if(lastAlertIds) {
        if(lastAlertIds.length > 0 && newAlertIds.length === 0) {
          playSample('none');
        }
        if(_.difference(newAlertIds, lastAlertIds).length > 0) {
          playSample('new');
        }
      }
      lastAlertIds = newAlertIds;

      $countdowns = null;
      updateCountdowns();
    }

    setInterval(updateCountdowns, 1000);

    $audioToggle.click(function() {
      if($audioToggle.hasClass('audio-off')) {
        $audioToggle.removeClass('audio-off');
        $audioToggle.addClass('audio-on');
        shouldPlaySounds = true;
      } else {
        $audioToggle.removeClass('audio-on');
        $audioToggle.addClass('audio-off');
        shouldPlaySounds = false;
      }
    });

    if(shouldPlaySounds) {
      $audioToggle.addClass('audio-on');
    } else {
      $audioToggle.addClass('audio-off');
    }

    new Refresher()
      .container('#container')
      .interval(<%= params[:refresh].to_i > 0 ? params[:refresh].to_i : 45 %> * 1000) // in seconds
      .callback(function() {
        $.get('/alerts/dashboard' + window.location.search, {limit: limit}).done(renderAlerts);
      }).render();

    renderAlerts({
      alerts: <%=raw Houston::Alerts::AlertPresenter.new(@alerts).to_json %>,
      count: <%= @count %>
    });
  });
</script>
<% end %>

app/views/houston/alerts/alerts/index.html.erb
<% content_for :title do %>
<h1 class="project-banner space-below">
  <span class="light"><%= @alerts.reject(&:suppressed?).count %></span> Alerts

  <%= render partial: "projects/keyboard_shortcuts" %>
  <%= link_to alerts_excel_path, id: "excel_export_button", class: "project-banner-btn" do %>
    <i class="fa fa-file-excel-o"></i>

    <span>
      Export<br />
      to Excel
    </span>
  <% end %>
</h1>
<% end %>

<div id="alerts" class="nomargin">
  <table id="unsuppressed_alerts" class="table table-sortable table-striped table-hoverable">
    <thead>
      <tr>
        <td class="table-margin"></td>
        <th class="houston-alert-project" data-attribute="projectSlug">Project</th>
        <th class="houston-alert-type" data-attribute="type">Type</th>
        <th class="houston-alert-number" data-attribute="type">Number</th>
        <th class="houston-alert-summary" data-attribute="summary">Summary</th>
        <th class="houston-alert-deadline sort-asc" data-attribute="deadline">Deadline</th>
        <th class="houston-alert-worker" data-attribute="checkedOutBy">Worker</th>
        <th class="houston-alert-suppress"></th>
        <td class="table-margin"></td>
      </tr>
    </thead>
    <tbody></tbody>
  </table>

  <hr>
  <h4>Suppressed</h4>

  <table id="suppressed_alerts" class="table table-striped table-hoverable">
    <thead>
      <tr>
        <td class="table-margin"></td>
        <th class="houston-alert-project" data-attribute="projectSlug">Project</th>
        <th class="houston-alert-type" data-attribute="type">Type</th>
        <th class="houston-alert-number" data-attribute="type">Number</th>
        <th class="houston-alert-summary" data-attribute="summary">Summary</th>
        <th class="houston-alert-deadline sort-asc" data-attribute="deadline">Deadline</th>
        <th class="houston-alert-worker" data-attribute="checkedOutBy">Worker</th>
        <th class="houston-alert-suppress"></th>
        <td class="table-margin"></td>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>

<% content_for :javascripts do %>
  <script type="text/javascript">
    $(function() {
      var alerts = new Houston.Alerts.Alerts(<%= raw Houston::Alerts::AlertPresenter.new(@alerts).to_json %>);
      new Houston.Alerts.AlertsView({
        el: document.getElementById('alerts'),
        alerts: alerts,
        projects: <%= raw MultiJson.dump(@projects) %>,
        workers: <%= raw Houston::Alerts::WorkerPresenter.new(
          Houston::Alerts.config.workers).to_json %>
      }).render();
    });
  </script>
<% end %>

app/views/houston/alerts/alerts/show.html.erb
<% content_for :meta do %>
  <%= tag "meta", property: "og:type", content: "website" %>
  <%= tag "meta", property: "og:site_name", content: (@alert.project ?
    "#{@alert.project.slug} / #{@alert.type} #{@alert.number}" :
    "#{@alert.type} #{@alert.number}") %>
  <%= tag "meta", property: "og:title", content: @alert.summary %>
  <%= tag "meta", property: "og:description", content: slackdown(@alert.text) %>
  <%= tag "meta", property: "og:url", content: @alert.url %>
<% end %>